### PR TITLE
created FAIR report via Github pages, updated NCEAS footer, and included additional code for analysis

### PR DESCRIPTION
**Pull request by cwbeltz**
Commit 1) this addresses issue #4

Commit 2) updated code for analyzing all three types of data. All changes are specific to the "Data-Fellowship" folder. I did not re-organize the repo in this PR.

Commit 3) multiple time series analysis/figures added. Note that work on figures 11 & 12 is ongoing.

Commit 4) converted analyses to a Github pages report. this commit uses the proposed structure, but only within my project folder.

### CODE REVIEW

**Comment by cwbeltz** [comment]
@mbjones @gothub Let me know if the proposed structure is ok from #3 and I welcome any comments on the Github pages presentation of the FAIR analyses.

**Comment by cwbeltz** [comment]
updated link to Github pages report: update link to Github pages report: https://cwbeltz.github.io/NCEAS-DF_FAIR_Metrics-Analysis/

**Comment by mbjones** [comment]
This looks great @cwbeltz ! Can you get it moved over to an NCEAS-hosted repository (probably this one) rather than in your personal repository. I looked through it and the results look intriguing. Looking forward to working with you on a paper on this -- I think there is a lot here.

**Comment by cwbeltz** [comment]
Will do @mbjones. I agree that some of the results are really interesting.... and looking forward to the paper as well!

**Comment by cwbeltz** [comment]
@mbjones All the files should now be in the metadig repo and working with new file paths. Github pages may need to be turned on in the repo's settings.

**Comment by mbjones** [comment]
LGTM. 🚀

**Pull request merged**
